In [5]:
import pandas as pd
import numpy as np

data = pd.read_excel("datasets/languageFinal.xlsx")
data

Skill         LearningStyle  \
0          Beginner       hands-on coding   
1          Beginner       hands-on coding   
2          Beginner       hands-on coding   
3      Intermediate    visual programming   
4      Intermediate    visual programming   
...             ...                   ...   
19995      Advanced    visual programming   
19996      Beginner       hands-on coding   
19997  Intermediate       hands-on coding   
19998      Advanced  Theoritical approach   
19999  Intermediate    visual programming   

                                  ProjectType PlatformCompatibility  \
0                          System Programming                    No   
1                                  Statistics                   Yes   
2                            Game Development                   Yes   
3                          System Programming                    No   
4                           Signal Processing                    No   
...                                       ...                   ...   
19995  Argumented Reality and Virtual Reality                    No   
19996                  Full-stack Development                   Yes   
19997                               Scripting                   Yes   
19998                  Mobile App Development                   Yes   
19999                      Internet of Things                   Yes   

      IndustrtTrends Ecosystems  Scalibility DataHandling Documentation  \
0               Much        Yes  Small Scale     Not sure      Not sure   
1         Not at all         No  Mix of Both           No      Not sure   
2               Rare        Yes  Large Scale           No      Not sure   
3               Rare   Not sure  Small Scale           No            No   
4               Rare        Yes  Mix of Both     Not sure            No   
...              ...        ...          ...          ...           ...   
19995           Rare   Not sure  Large Scale           No      Not sure   
19996           Much         No  Large Scale           No      Not sure   
19997     Not at all         No  Mix of Both          Yes           Yes   
19998           Rare        Yes  Large Scale          Yes            No   
19999     Not at all         No  Mix of Both           No            No   

                        Language  
0                              C  
1                              R  
2                        Scratch  
3                       Assembly  
4                   C++ (OpenCV)  
...                          ...  
19995                        C++  
19996      HTML, CSS, JavaScript  
19997                       Bash  
19998  React Native (JavaScript)  
19999                        C++  

[20000 rows x 10 columns]

In [6]:
df = pd.get_dummies(data, columns=['Skill', 'LearningStyle', 'PlatformCompatibility', 'IndustrtTrends','Ecosystems','Scalibility','DataHandling','Documentation'])
df

ProjectType                   Language  \
0                          System Programming                          C   
1                                  Statistics                          R   
2                            Game Development                    Scratch   
3                          System Programming                   Assembly   
4                           Signal Processing               C++ (OpenCV)   
...                                       ...                        ...   
19995  Argumented Reality and Virtual Reality                        C++   
19996                  Full-stack Development      HTML, CSS, JavaScript   
19997                               Scripting                       Bash   
19998                  Mobile App Development  React Native (JavaScript)   
19999                      Internet of Things                        C++   

       Skill_Advanced  Skill_Beginner  Skill_Intermediate  \
0                   0               1                   0   
1                   0               1                   0   
2                   0               1                   0   
3                   0               0                   1   
4                   0               0                   1   
...               ...             ...                 ...   
19995               1               0                   0   
19996               0               1                   0   
19997               0               0                   1   
19998               1               0                   0   
19999               0               0                   1   

       LearningStyle_Theoritical approach  LearningStyle_hands-on coding  \
0                                       0                              1   
1                                       0                              1   
2                                       0                              1   
3                                       0                              0   
4                                       0                              0   
...                                   ...                            ...   
19995                                   0                              0   
19996                                   0                              1   
19997                                   0                              1   
19998                                   1                              0   
19999                                   0                              0   

       LearningStyle_visual programming  PlatformCompatibility_No  \
0                                     0                         1   
1                                     0                         0   
2                                     0                         0   
3                                     1                         1   
4                                     1                         1   
...                                 ...                       ...   
19995                                 1                         1   
19996                                 0                         0   
19997                                 0                         0   
19998                                 0                         0   
19999                                 1                         0   

       PlatformCompatibility_Yes  ...  Ecosystems_Yes  \
0                              0  ...               1   
1                              1  ...               0   
2                              1  ...               1   
3                              0  ...               0   
4                              0  ...               1   
...                          ...  ...             ...   
19995                          0  ...               0   
19996                          1  ...               0   
19997                          1  ...               0   
19998                          1  ...               1   
19999              

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Apply Label Encoding to all columns in the DataFrame
df_encoded = df.apply(label_encoder.fit_transform)
df_encoded

ProjectType  Language  Skill_Advanced  Skill_Beginner  \
0               24         4               0               1   
1               22        23               0               1   
2               16        28               0               1   
3               24         2               0               0   
4               21         7               0               0   
...            ...       ...             ...             ...   
19995            2         6               1               0   
19996           15        11               0               1   
19997           20         3               0               0   
19998           19        25               1               0   
19999           18         6               0               0   

       Skill_Intermediate  LearningStyle_Theoritical approach  \
0                       0                                   0   
1                       0                                   0   
2                       0                                   0   
3                       1                                   0   
4                       1                                   0   
...                   ...                                 ...   
19995                   0                                   0   
19996                   0                                   0   
19997                   1                                   0   
19998                   0                                   1   
19999                   1                                   0   

       LearningStyle_hands-on coding  LearningStyle_visual programming  \
0                                  1                                 0   
1                                  1                                 0   
2                                  1                                 0   
3                                  0                                 1   
4                                  0                                 1   
...                              ...                               ...   
19995                              0                                 1   
19996                              1                                 0   
19997                              1                                 0   
19998                              0                                 0   
19999                              0                                 1   

       PlatformCompatibility_No  PlatformCompatibility_Yes  ...  \
0                             1                          0  ...   
1                             0                          1  ...   
2                             0                          1  ...   
3                             1                          0  ...   
4                             1                          0  ...   
...                         ...                        ...  ...   
19995                         1                          0  ...   
19996                         0                          1  ...   
19997                         0                          1  ...   
19998                         0                          1  ...   
19999                         0                          1  ...   

       Ecosystems_Yes  Scalibility_Large Scale  Scalibility_Mix of Both  \
0                   1                        0                        0   
1                   0                        0                        1   
2                   1                        1                        0   
3                   0                        0                        0   
4                   1                        0                        1   
...               ...                      ...                      ...   
19995               0                        1                        0   
19996               0                        1                        0   
19997               0                        0                        1   
19998        

In [8]:
x = df_encoded.iloc[:, df_encoded.columns != 'Language'].values
x[0]

array([24,  0,  1,  0,  0,  1,  0,  1,  0,  1,  0,  0,  0,  0,  1,  0,  0,
        1,  0,  1,  0,  0,  1,  0])

In [9]:
y = df_encoded.iloc[:,df_encoded.columns == 'Language'].values
y

array([[ 4],
       [23],
       [28],
       ...,
       [ 3],
       [25],
       [ 6]])

In [10]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Load or prepare your dataset
# X contains input features
# y contains multivariate output variables

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# # Create a Multi-Output Decision Trees model
base_model = DecisionTreeRegressor()
model = MultiOutputRegressor(base_model)

# # Train the model on the training data
model.fit(X_train, y_train)

# # Make predictions on the test data
y_pred = model.predict(X_test)

print(y_pred)

[[13.]
 [16.]
 [ 3.]
 ...
 [ 4.]
 [34.]
 [20.]]


In [11]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
ac

0.995

In [12]:
y_pred[1242]

array([6.])

In [13]:
y_test[1242]

array([6])

In [14]:
X_test[123]

array([8, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0])

In [15]:
from sklearn.preprocessing import LabelEncoder

# Assuming you have the original 'ProjectType' column
original_project_type_column = df['ProjectType']
original_language_column = df['Language']

# Create and fit the LabelEncoder
label_encoder_project_type = LabelEncoder()
label_encoder_project_type.fit(original_project_type_column)

label_encoder_language = LabelEncoder()
label_encoder_language.fit(original_language_column)

# Example: Suppose 14 is the label-encoded value for 'ProjectType'

for i in range(0,35):

    encoded_value = i

    original_language = label_encoder_language.inverse_transform([encoded_value])[0]
    
    
    print(i,original_language)


0 Angular.js (JavaScript)
1 Arduino (C++)
2 Assembly
3 Bash
4 C
5 C#
6 C++
7 C++ (OpenCV)
8 Flutter (Dart)
9 Go
10 Godot (GDScript)
11 HTML, CSS, JavaScript
12 Java
13 JavaScript
14 Kotlin
15 Kotlin (Android)
16 MATLAB
17 Node.js
18 PHP
19 PowerShell
20 Python
21 Python (NumPy, SciPy)
22 Python (NumPy, pandas, SciPy)
23 R
24 React
25 React Native (JavaScript)
26 React.js (JavaScript)
27 SPSS
28 Scratch
29 Shell Scripting
30 Swift
31 Swift (iOS)
32 TypeScript
33 Unity (C#)
34 Vue.js


In [16]:
from sklearn.preprocessing import LabelEncoder

# Assuming you have the original 'ProjectType' column
original_project_type_column = df['ProjectType']
original_language_column = df['Language']

# Create and fit the LabelEncoder
label_encoder_project_type = LabelEncoder()
label_encoder_project_type.fit(original_project_type_column)

label_encoder_language = LabelEncoder()
label_encoder_language.fit(original_language_column)

# Example: Suppose 14 is the label-encoded value for 'ProjectType'

for i in range(0,26):

    encoded_value = i

    # Convert the label-encoded value back to the original form
    original_value_project_type = label_encoder_project_type.inverse_transform([encoded_value])[0]

    original_language = label_encoder_language.inverse_transform([encoded_value])[0]
    
    
    print(original_value_project_type)


API Development
Android App Development
Argumented Reality and Virtual Reality
Artificial Intelligence
Automation
Blockchain Development
Cloud Computing
Cybersecurity
Data Analysis
Data Science
Desktop Application Development
DevOps
E-commerce
Embedded Systems
Frontend Development
Full-stack Development
Game Development
Healthcare IT
Internet of Things
Mobile App Development
Scripting
Signal Processing
Statistics
System Administration
System Programming
Web Development


In [17]:
import pickle
pickle.dump(model,open('models/modelLanguageFinal.pkl', 'wb'))

In [20]:
import joblib
import numpy as np

modelLanguage = joblib.load('modelLanguage.pkl')

user_input = input()  # This line reads the input sent from Node.js

integer_array = [float(x) for x in user_input.split(",")]


predictionLanguage = modelLanguage.predict([integer_array])

print(predictionLanguage)

FileNotFoundError: [Errno 2] No such file or directory: 'modelLanguage.pkl'

In [4]:
!pip install sklearn

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detai